name: Upload Directory to Target Repo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: 'ArthurKun21/test-github-upload-output'
          token: ${{ secrets.UPLOAD_REPO }}
          fetch-depth: 0
          path: 'other-repo'
                
      - name: Upload Directory
        run: |
          # Configure git
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Clean and copy files
          cd other-repo
          rm -rf output || true  # Clean target directory
          cd ..
          cp -r output other-repo/output
          
          # Commit and push changes only if there are modifications
          cd other-repo
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "Upload output directory"
            git push

            echo "OUTPUT_CHANGES=true" >> $GITHUB_ENV
          else
            echo "No changes detected"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.UPLOAD_REPO }}
      
      - name: Trigger workflow in target repository
        if: env.OUTPUT_CHANGES == 'true'
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.UPLOAD_REPO }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'ArthurKun21',
              repo: 'test-github-upload-output',
              workflow_id: 'release.yml',  
              ref: 'main'  
            });